spring:
  application:
    name: msclientes

server:
  port: 0
  
eureka:
  client:
    service-url:
      defaultZone: http://kleberlzms-eureka-user:erlseeakrer-sbzluk-ume@kleberlzms-eureka:8762/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*' # Expondo os endpoints pro Actuator (Somente os MicroServiços)

logging:
  file:
    name: ./logs/log-file.log # Acessar o LOG no browser através do Actuator


